model_config:
  base_api: "https://your-provider.com"
  api_key: "sk-your-secret-key"
  model: "gpt-4o"
  temperature: 0.4

server:
  port: 8000

monitoring:
  langsmith_base_api: null
  langsmith_api_key: null
